In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import scipy as sp

In [5]:
# using the Csv file 
df = pd.read_csv('Car_sale_ads_short.csv')  
  
# Checking the first 5 entries of dataset 
df.head()

,Index,Price,Currency,Condition,Vehicle_brand,Vehicle_model,Vehicle_version,Vehicle_generation,Production_year,Mileage_km,...,Transmission,Type,Doors_number,Colour,Origin_country,First_owner,First_registration_date,Offer_publication_date,Offer_location,Features
0,0,86200,PLN,New,Abarth,595,NaN,NaN,2021,1.0,...,Manual,small_cars,3.0,gray,NaN,NaN,NaN,04/05/2021,"ul. Jubilerska 6 - 04-190 Warszawa, Mazowiecki...",[]
1,1,43500,PLN,Used,Abarth,Other,NaN,NaN,1974,59000.0,...,Manual,coupe,2.0,silver,NaN,NaN,NaN,03/05/2021,"kanonierska12 - 04-425 Warszawa, Rembertów (Po...",[]
2,2,44900,PLN,Used,Abarth,500,NaN,NaN,2018,52000.0,...,Automatic,small_cars,3.0,silver,NaN,NaN,NaN,03/05/2021,"Warszawa, Mazowieckie, Białołęka","['ABS', 'Electric front windows', 'Drivers air..."
3,3,39900,PLN,Used,Abarth,500,NaN,NaN,2012,29000.0,...,Manual,small_cars,3.0,gray,NaN,NaN,NaN,30/04/2021,"Jaworzno, Śląskie","['ABS', 'Electric front windows', 'Drivers air..."
4,4,97900,PLN,New,Abarth,595,NaN,NaN,2021,600.0,...,Manual,small_cars,3.0,blue,NaN,NaN,NaN,30/04/2021,"ul. Gorzysława 9 - 61-057 Poznań, Nowe Miasto ...","['ABS', 'Electrically adjustable mirrors', 'Pa..."

In [6]:
headers = ["Index","Price","Currency","Condition","Vehicle_brand","Vehicle_model","Vehicle_version","Vehicle_generation","Production_year","Mileage_km","Power_HP","Displacement_cm3","Fuel_type","CO2_emissions","Drive","Transmission","Type","Doors_number","Colour","Origin_country","First_owner","First_registration_date","Offer_publication_date","Offer_location","Features"] 
  
df.columns=headers 
df.head()

,Index,Price,Currency,Condition,Vehicle_brand,Vehicle_model,Vehicle_version,Vehicle_generation,Production_year,Mileage_km,...,Transmission,Type,Doors_number,Colour,Origin_country,First_owner,First_registration_date,Offer_publication_date,Offer_location,Features
0,0,86200,PLN,New,Abarth,595,NaN,NaN,2021,1.0,...,Manual,small_cars,3.0,gray,NaN,NaN,NaN,04/05/2021,"ul. Jubilerska 6 - 04-190 Warszawa, Mazowiecki...",[]
1,1,43500,PLN,Used,Abarth,Other,NaN,NaN,1974,59000.0,...,Manual,coupe,2.0,silver,NaN,NaN,NaN,03/05/2021,"kanonierska12 - 04-425 Warszawa, Rembertów (Po...",[]
2,2,44900,PLN,Used,Abarth,500,NaN,NaN,2018,52000.0,...,Automatic,small_cars,3.0,silver,NaN,NaN,NaN,03/05/2021,"Warszawa, Mazowieckie, Białołęka","['ABS', 'Electric front windows', 'Drivers air..."
3,3,39900,PLN,Used,Abarth,500,NaN,NaN,2012,29000.0,...,Manual,small_cars,3.0,gray,NaN,NaN,NaN,30/04/2021,"Jaworzno, Śląskie","['ABS', 'Electric front windows', 'Drivers air..."
4,4,97900,PLN,New,Abarth,595,NaN,NaN,2021,600.0,...,Manual,small_cars,3.0,blue,NaN,NaN,NaN,30/04/2021,"ul. Gorzysława 9 - 61-057 Poznań, Nowe Miasto ...","['ABS', 'Electrically adjustable mirrors', 'Pa..."

In [14]:
data = df 
  
# Finding the missing values 
data.isna().any() 
  
# Finding if missing values  
data.isnull().any()

Index                      False
Price                      False
Currency                   False
Condition                  False
Vehicle_brand              False
Vehicle_model              False
Vehicle_version             True
Vehicle_generation          True
Production_year            False
Mileage_km                  True
Power_HP                    True
Displacement_cm3            True
Fuel_type                  False
CO2_emissions               True
Drive                       True
Transmission                True
Type                       False
Doors_number                True
Colour                     False
Origin_country              True
First_owner                 True
First_registration_date     True
Offer_publication_date     False
Offer_location             False
Features                   False
dtype: bool

In [21]:
print(data.columns) 
  
# checking the data type of each column 
data.dtypes 
data.head(20)

Index(['Index', 'Price', 'Currency', 'Condition', 'Vehicle_brand',
       'Vehicle_model', 'Vehicle_version', 'Vehicle_generation',
       'Production_year', 'Mileage_km', 'Power_HP', 'Displacement_cm3',
       'Fuel_type', 'CO2_emissions', 'Drive', 'Transmission', 'Type',
       'Doors_number', 'Colour', 'Origin_country', 'First_owner',
       'First_registration_date', 'Offer_publication_date', 'Offer_location',
       'Features', 'date', 'Offer_publication_date_as_date'],
      dtype='object')

,Index,Price,Currency,Condition,Vehicle_brand,Vehicle_model,Vehicle_version,Vehicle_generation,Production_year,Mileage_km,...,Doors_number,Colour,Origin_country,First_owner,First_registration_date,Offer_publication_date,Offer_location,Features,date,Offer_publication_date_as_date
0,0,86200,PLN,New,Abarth,595,NaN,NaN,2021,1.0,...,3.0,gray,NaN,NaN,NaN,04/05/2021,"ul. Jubilerska 6 - 04-190 Warszawa, Mazowiecki...",[],2021-05-04,2021-05-04
1,1,43500,PLN,Used,Abarth,Other,NaN,NaN,1974,59000.0,...,2.0,silver,NaN,NaN,NaN,03/05/2021,"kanonierska12 - 04-425 Warszawa, Rembertów (Po...",[],2021-05-03,2021-05-03
2,2,44900,PLN,Used,Abarth,500,NaN,NaN,2018,52000.0,...,3.0,silver,NaN,NaN,NaN,03/05/2021,"Warszawa, Mazowieckie, Białołęka","['ABS', 'Electric front windows', 'Drivers air...",2021-05-03,2021-05-03
3,3,39900,PLN,Used,Abarth,500,NaN,NaN,2012,29000.0,...,3.0,gray,NaN,NaN,NaN,30/04/2021,"Jaworzno, Śląskie","['ABS', 'Electric front windows', 'Drivers air...",2021-04-30,2021-04-30
4,4,97900,PLN,New,Abarth,595,NaN,NaN,2021,600.0,...,3.0,blue,NaN,NaN,NaN,30/04/2021,"ul. Gorzysława 9 - 61-057 Poznań, Nowe Miasto ...","['ABS', 'Electrically adjustable mirrors', 'Pa...",2021-04-30,2021-04-30
5,5,62950,PLN,Used,Abarth,595,NaN,NaN,2016,46060.0,...,3.0,gray,Germany,Yes,15/03/2016,30/04/2021,"Modlińska 157 - 03-186 Warszawa, Białołęka (Po...","['ABS', 'Electric front windows', 'Drivers air...",2021-04-30,2021-04-30
6,6,69900,PLN,Used,Abarth,595,NaN,NaN,2021,2900.0,...,2.0,black,Germany,NaN,25/02/2021,29/04/2021,"Żary, żarski, Lubuskie",[],2021-04-29,2021-04-29
7,7,69900,PLN,Used,Abarth,500,NaN,NaN,2019,20000.0,...,3.0,white,Poland,Yes,NaN,29/04/2021,"Ojcowska 2 - 02-918 Warszawa, Mokotów (Polska)","['ABS', 'Electrically adjustable mirrors', 'Pa...",2021-04-29,2021-04-29
8,8,120750,PLN,New,Abarth,595,NaN,NaN,2021,1.0,...,3.0,blue,NaN,NaN,NaN,03/05/2021,"ul. Gorzysława 9 - 61-057 Poznań, Nowe Miasto ...","['ABS', 'Electrically adjustable mirrors', 'Pa...",2021-05-03,2021-05-03
9,9,93100,PLN,New,Abarth,595,NaN,NaN,2021,1.0,...,3.0,gray,NaN,NaN,NaN,03/05/2021,"ul. Gorzysława 9 - 61-057 Poznań, Nowe Miasto ...","['ABS', 'Electrically adjustable mirrors', 'Pa...",2021-05-03,2021-05-03
10,10,67000,PLN,Used,Abarth,595,NaN,NaN,2018,38000.0,...,3.0,white,Poland,NaN,NaN,25/04/2021,"Gdańsk, Pomorskie, Śródmieście","['ABS', 'Electric front windows', 'Passengers ...",2021-04-25,2021-04-25
11,11,31900,PLN,Used,Abarth,Grande Punto,NaN,NaN,2010,179000.0,...,3.0,white,NaN,NaN,29/04/2010,25/04/2021,"Bielsko-Biała, Śląskie","['ABS', 'Electric front windows', 'Drivers air...",2021-04-25,2021-04-25
12,12,70000,PLN,Used,Abarth,595,NaN,NaN,2017,18470.0,...,3.0,black,Germany,NaN,09/11/2017,04/05/2021,"Rzeszów, Podkarpackie","['ABS', 'Immobilizer', 'Factory radio', 'ASR (...",2021-05-04,2021-05-04
13,13,38500,PLN,Used,Abarth,500,NaN,NaN,2015,117000.0,...,3.0,gray,NaN,Yes,NaN,04/05/2021,"Sulechów, zielonogórski, Lubuskie","['ABS', 'Bluetooth', 'Rain sensor', 'Panoramic...",2021-05-04,2021-05-04
14,14,41400,PLN,Used,Abarth,500,NaN,NaN,2014,79233.0,...,3.0,red,Poland,NaN,18/05/2015,04/05/2021,"Koszalin, Zachodniopomorskie","['ABS', 'Electric front windows', 'Drivers air...",2021-05-04,2021-05-04
15,15,36000,PLN,Used,Abarth,Other,NaN,NaN,2012,82000.0,...,3.0,black,Poland,NaN,27/04/2012,23/04/2021,"Zgorzelec, zgorzelecki, Dolnośląskie","['ABS', 'Electric front windows', 'Power steer...",2021-04-23,2021-04-23
16,16,80900,PLN,New,Abarth,595,NaN,NaN,2020,1.0,...,3.0,red,NaN,NaN,NaN,29/04/2021,"ul. Jubilerska 6 - 04-190 Warszawa, Mazowiecki...",[],2021-04-29,2021-04-29
17,17,127921,PLN,New,Abarth,595,NaN,NaN,2021,3.0,...,3.0,blue,NaN,NaN,NaN,29/04/2021,"ul. Karkonoska 45 - 53-015 Wrocław, Dolnośląsk...","['ABS', 'Electrically adjustable mirrors', 'Pa...",2021-04-29,2021-04-29
18,18,70900,PLN,Used,Abarth,595,NaN,NaN,2019,11000.0,...,2.0,yellow,Poland,Yes,NaN,04/05/2021,"Lublin, Lubelskie","['ABS', 'Electric front windows', 'Drivers air...",2021-05-04,2021-05-04
19,19,22900,PLN,Used,Abarth,Grande Punto,NaN,NaN,2009,182000.0,...,3.0,white,Germany,NaN,29/05/2009,04/05/2021,"Jarocin, jarociński, Wielkopolskie","['ABS', 'Electric front windows', 'Drivers air...",2021-05-04,2021-05-04

In [24]:
df["Offer_publication_date_as_date"] = pd.to_datetime(df['Offer_publication_date'], dayfirst=True)
df["First_registration_date_as_date"] = pd.to_datetime(df['First_registration_date'], dayfirst=True, errors='coerce')
df = df.drop(columns=['Offer_publication_date', 'First_registration_date'])

df.head(20)

,Index,Price,Currency,Condition,Vehicle_brand,Vehicle_model,Vehicle_version,Vehicle_generation,Production_year,Mileage_km,...,Type,Doors_number,Colour,Origin_country,First_owner,Offer_location,Features,date,Offer_publication_date_as_date,First_registration_date_as_date
0,0,86200,PLN,New,Abarth,595,NaN,NaN,2021,1.0,...,small_cars,3.0,gray,NaN,NaN,"ul. Jubilerska 6 - 04-190 Warszawa, Mazowiecki...",[],2021-05-04,2021-05-04,NaT
1,1,43500,PLN,Used,Abarth,Other,NaN,NaN,1974,59000.0,...,coupe,2.0,silver,NaN,NaN,"kanonierska12 - 04-425 Warszawa, Rembertów (Po...",[],2021-05-03,2021-05-03,NaT
2,2,44900,PLN,Used,Abarth,500,NaN,NaN,2018,52000.0,...,small_cars,3.0,silver,NaN,NaN,"Warszawa, Mazowieckie, Białołęka","['ABS', 'Electric front windows', 'Drivers air...",2021-05-03,2021-05-03,NaT
3,3,39900,PLN,Used,Abarth,500,NaN,NaN,2012,29000.0,...,small_cars,3.0,gray,NaN,NaN,"Jaworzno, Śląskie","['ABS', 'Electric front windows', 'Drivers air...",2021-04-30,2021-04-30,NaT
4,4,97900,PLN,New,Abarth,595,NaN,NaN,2021,600.0,...,small_cars,3.0,blue,NaN,NaN,"ul. Gorzysława 9 - 61-057 Poznań, Nowe Miasto ...","['ABS', 'Electrically adjustable mirrors', 'Pa...",2021-04-30,2021-04-30,NaT
5,5,62950,PLN,Used,Abarth,595,NaN,NaN,2016,46060.0,...,small_cars,3.0,gray,Germany,Yes,"Modlińska 157 - 03-186 Warszawa, Białołęka (Po...","['ABS', 'Electric front windows', 'Drivers air...",2021-04-30,2021-04-30,2016-03-15
6,6,69900,PLN,Used,Abarth,595,NaN,NaN,2021,2900.0,...,small_cars,2.0,black,Germany,NaN,"Żary, żarski, Lubuskie",[],2021-04-29,2021-04-29,2021-02-25
7,7,69900,PLN,Used,Abarth,500,NaN,NaN,2019,20000.0,...,small_cars,3.0,white,Poland,Yes,"Ojcowska 2 - 02-918 Warszawa, Mokotów (Polska)","['ABS', 'Electrically adjustable mirrors', 'Pa...",2021-04-29,2021-04-29,NaT
8,8,120750,PLN,New,Abarth,595,NaN,NaN,2021,1.0,...,small_cars,3.0,blue,NaN,NaN,"ul. Gorzysława 9 - 61-057 Poznań, Nowe Miasto ...","['ABS', 'Electrically adjustable mirrors', 'Pa...",2021-05-03,2021-05-03,NaT
9,9,93100,PLN,New,Abarth,595,NaN,NaN,2021,1.0,...,small_cars,3.0,gray,NaN,NaN,"ul. Gorzysława 9 - 61-057 Poznań, Nowe Miasto ...","['ABS', 'Electrically adjustable mirrors', 'Pa...",2021-05-03,2021-05-03,NaT
10,10,67000,PLN,Used,Abarth,595,NaN,NaN,2018,38000.0,...,small_cars,3.0,white,Poland,NaN,"Gdańsk, Pomorskie, Śródmieście","['ABS', 'Electric front windows', 'Passengers ...",2021-04-25,2021-04-25,NaT
11,11,31900,PLN,Used,Abarth,Grande Punto,NaN,NaN,2010,179000.0,...,city_cars,3.0,white,NaN,NaN,"Bielsko-Biała, Śląskie","['ABS', 'Electric front windows', 'Drivers air...",2021-04-25,2021-04-25,2010-04-29
12,12,70000,PLN,Used,Abarth,595,NaN,NaN,2017,18470.0,...,small_cars,3.0,black,Germany,NaN,"Rzeszów, Podkarpackie","['ABS', 'Immobilizer', 'Factory radio', 'ASR (...",2021-05-04,2021-05-04,2017-11-09
13,13,38500,PLN,Used,Abarth,500,NaN,NaN,2015,117000.0,...,city_cars,3.0,gray,NaN,Yes,"Sulechów, zielonogórski, Lubuskie","['ABS', 'Bluetooth', 'Rain sensor', 'Panoramic...",2021-05-04,2021-05-04,NaT
14,14,41400,PLN,Used,Abarth,500,NaN,NaN,2014,79233.0,...,small_cars,3.0,red,Poland,NaN,"Koszalin, Zachodniopomorskie","['ABS', 'Electric front windows', 'Drivers air...",2021-05-04,2021-05-04,2015-05-18
15,15,36000,PLN,Used,Abarth,Other,NaN,NaN,2012,82000.0,...,city_cars,3.0,black,Poland,NaN,"Zgorzelec, zgorzelecki, Dolnośląskie","['ABS', 'Electric front windows', 'Power steer...",2021-04-23,2021-04-23,2012-04-27
16,16,80900,PLN,New,Abarth,595,NaN,NaN,2020,1.0,...,small_cars,3.0,red,NaN,NaN,"ul. Jubilerska 6 - 04-190 Warszawa, Mazowiecki...",[],2021-04-29,2021-04-29,NaT
17,17,127921,PLN,New,Abarth,595,NaN,NaN,2021,3.0,...,small_cars,3.0,blue,NaN,NaN,"ul. Karkonoska 45 - 53-015 Wrocław, Dolnośląsk...","['ABS', 'Electrically adjustable mirrors', 'Pa...",2021-04-29,2021-04-29,NaT
18,18,70900,PLN,Used,Abarth,595,NaN,NaN,2019,11000.0,...,small_cars,2.0,yellow,Poland,Yes,"Lublin, Lubelskie","['ABS', 'Electric front windows', 'Drivers air...",2021-05-04,2021-05-04,NaT
19,19,22900,PLN,Used,Abarth,Grande Punto,NaN,NaN,2009,182000.0,...,city_cars,3.0,white,Germany,NaN,"Jarocin, jarociński, Wielkopolskie","['ABS', 'Electric front windows', 'Drivers air...",2021-05-04,2021-05-04,2009-05-29